version: '3.8'

services:
  remotion-ssr:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REMOTION_CONCURRENCY=2
      - REMOTION_API_KEY=${REMOTION_API_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
    volumes:
      # Make output directory persistent with named volume
      - remotion_output:/app/output
    restart: unless-stopped
    mem_limit: 2g
    cpus: '1.0'
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  remotion_output:
    driver: local 