# Multi-stage build for BlueFx Next.js app
FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy package files
COPY app/package*.json ./
COPY app/yarn.lock* ./

# Install dependencies
RUN npm ci --only=production --legacy-peer-deps

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app

COPY app/package*.json ./
COPY app/yarn.lock* ./
RUN npm ci --legacy-peer-deps

COPY app/ .

# Set build-time environment variables
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_VIDEO_EDITOR_URL
ARG SUPABASE_SERVICE_ROLE_KEY
ARG PERPLEXITY_API_KEY
ARG PEXELS_API_KEY
ARG OPENAI_API_KEY
ARG REPLICATE_API_TOKEN
ARG HEDRA_API_KEY
ARG YOUTUBE_API_KEY
ARG SIEVE_API_KEY
ARG SHOTSTACK_API_KEY
ARG RAPIDAPI_KEY
ARG ENABLE_AI_FEATURES
ARG ZAPIER_WEBHOOK_SECRET
ARG CLICKBANK_PRODUCT_ID
ARG GOOGLE_GEMENI_API_KEY

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_VIDEO_EDITOR_URL=$NEXT_PUBLIC_VIDEO_EDITOR_URL
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV PERPLEXITY_API_KEY=$PERPLEXITY_API_KEY
ENV PEXELS_API_KEY=$PEXELS_API_KEY
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV REPLICATE_API_TOKEN=$REPLICATE_API_TOKEN
ENV HEDRA_API_KEY=$HEDRA_API_KEY
ENV YOUTUBE_API_KEY=$YOUTUBE_API_KEY
ENV SIEVE_API_KEY=$SIEVE_API_KEY
ENV SHOTSTACK_API_KEY=$SHOTSTACK_API_KEY
ENV RAPIDAPI_KEY=$RAPIDAPI_KEY
ENV ENABLE_AI_FEATURES=$ENABLE_AI_FEATURES
ENV ZAPIER_WEBHOOK_SECRET=$ZAPIER_WEBHOOK_SECRET
ENV CLICKBANK_PRODUCT_ID=$CLICKBANK_PRODUCT_ID
ENV GOOGLE_GEMENI_API_KEY=$GOOGLE_GEMENI_API_KEY

# Build the application
RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy built application
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["node", "server.js"]