version: '3.8'

services:
  # Main BlueFX Next.js App
  bluefx-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${APP_NODE_ENV:-production}
      - PORT=3000
      - REMOTION_SERVICE_URL=http://remotion:3001
      - REACT_VIDEO_EDITOR_URL=http://react-video-editor:3002
      - DATABASE_URL=${APP_DATABASE_URL}
      - NEXTAUTH_SECRET=${APP_NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${APP_NEXTAUTH_URL}
    depends_on:
      - remotion
      - react-video-editor
    restart: unless-stopped
    mem_limit: 1g
    cpus: '0.5'

  # React Video Editor Next.js App
  react-video-editor:
    build:
      context: ./react-video-editor
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=${EDITOR_NODE_ENV:-production}
      - PORT=3002
      - REMOTION_SERVICE_URL=http://remotion:3001
      - PEXELS_API_KEY=${EDITOR_PEXELS_API_KEY}
      - UPLOAD_SERVICE_URL=${EDITOR_UPLOAD_SERVICE_URL}
    depends_on:
      - remotion
    restart: unless-stopped
    mem_limit: 1g
    cpus: '0.5'

  # Remotion Server
  remotion:
    build:
      context: ./remotion
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${REMOTION_NODE_ENV:-production}
      - PORT=3001
      - REMOTION_CONCURRENCY=${REMOTION_CONCURRENCY:-2}
      - REMOTION_API_KEY=${REMOTION_API_KEY}
      - CORS_ORIGIN=${REMOTION_CORS_ORIGIN:-*}
    volumes:
      - remotion_output:/app/output
      - remotion_output_local:/app/output_local
    restart: unless-stopped
    mem_limit: 2g
    cpus: '1.0'
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  remotion_output:
    driver: local
  remotion_output_local:
    driver: local

networks:
  default:
    driver: bridge